name: rating-prediction
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - ipykernel
  - ipython
  - jupyter_client
  - jupyter_core
  - numpy=2.2.5
  - pandas=2.2.3
  - scikit-learn=1.6.1
  - scipy=1.15.3
  - nltk=3.9.1
  - xgboost=3.0.1
  - spacy
  - pip:
      - scikit-learn-intelex==2025.5.0
      - intelex==0.0.30
      - tbb==2022.1.0
      - tqdm==4.67.1
      - regex==2024.11.6
      - requests==2.32.3
      - click==8.2.0
      - joblib==1.5.0
      - pytz==2025.2
      - tzdata==2025.2
      - charset-normalizer==3.4.2
      - urllib3==2.4.0
      - certifi==2025.4.26
      - daal==2025.5.0
      - tcmlib==1.3.0
      - idna==3.10
